#!/usr/bin/env python3
"""Standalone migration script: convert old single-file config.yaml to the new
modular config/ folder structure.

Produces:
    <output>/
        main.yaml                       # !include references + default_profile
        audio.yaml                      # domain configs (one per top-level key)
        asr.yaml
        llm.yaml
        content_types.yaml
        song.yaml
        output.yaml
        padding.yaml
        dialogue.yaml
        highlight.yaml
        funny.yaml
        cringe.yaml
        daily_summary.yaml
        cut_copy.yaml
        profiles/
            <profile_name>.yaml         # one file per profile
        streamer_dictionary.json        # copied from source if present
        cut_copy.conf                   # copied from source if present

Usage:
    python scripts/migrate_config.py <old-config.yaml> --output config/local/
    python scripts/migrate_config.py <old-config.yaml> --output config/local/ --dry-run
    python scripts/migrate_config.py <old-config.yaml> --output config/local/ --overwrite
    python scripts/migrate_config.py --help

Requirements:
    - PyYAML:  pip install PyYAML
    - Python 3.10+

This script is STANDALONE — it does NOT import from dd_clip_miner_llm.
"""
from __future__ import annotations

import argparse
import json
import shutil
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    sys.exit("PyYAML is required. Install with: pip install PyYAML")

# ── Constants ───────────────────────────────────────────────────────────────

GENERATED_HEADER = """\
# =============================================================================
# GENERATED BY migrate_config.py — DO NOT EDIT MANUALLY
#
# This file was automatically produced by the config migration tool.
# To make changes:
#   1. Edit the original single-file config and re-run the migration, OR
#   2. Edit the individual domain/profile YAML files directly.
# =============================================================================
"""

# Top-level keys that become domain YAML files (in order of main.yaml appearance)
DOMAIN_KEYS: tuple[str, ...] = (
    "audio",
    "asr",
    "llm",
    "content_types",
    "song",
    "output",
    "padding",
    "dialogue",
    "highlight",
    "funny",
    "cringe",
    "daily_summary",
    "cut_copy",
)

# Internal keys that do NOT become domain files
META_KEYS: frozenset[str] = frozenset({"profiles", "default_profile"})

# Companion files to copy from the old config's directory
COMPANION_FILES: tuple[tuple[str, str], ...] = (
    ("streamer_dictionary.json", "streamer_dictionary.json"),
    ("cut_copy.conf", "cut_copy.conf"),
)

# ── YAML helpers ────────────────────────────────────────────────────────────


def _yaml_dump(data: object) -> str:
    """Serialize data as YAML with consistent formatting."""
    return yaml.dump(
        data,
        default_flow_style=False,
        allow_unicode=True,
        sort_keys=False,
        width=120,
    )


def _load_old_config(path: Path) -> dict:
    """Parse the old-format YAML file. Exits with a clear message on failure."""
    try:
        with open(path, "r", encoding="utf-8") as handle:
            data = yaml.safe_load(handle)
    except yaml.YAMLError as exc:
        sys.exit(f"Error: Invalid YAML in '{path}':\n  {exc}")
    except OSError as exc:
        sys.exit(f"Error: Cannot read '{path}':\n  {exc}")

    if data is None:
        sys.exit(f"Error: '{path}' is empty — nothing to migrate.")

    if not isinstance(data, dict):
        sys.exit(
            f"Error: '{path}' does not contain a YAML mapping (dict). "
            f"Got: {type(data).__name__}"
        )
    return data


def _write_file(dest: Path, content: str) -> None:
    """Write content to dest, creating parent directories."""
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(content, encoding="utf-8")


def _strip_header(content: str) -> str:
    """Remove leading comment lines and blank lines to extract pure YAML data."""
    lines = content.split("\n")
    start = 0
    for i, line in enumerate(lines):
        stripped = line.strip()
        if stripped == "" or stripped.startswith("#"):
            continue
        start = i
        break
    return "\n".join(lines[start:])


# ── Core migration ──────────────────────────────────────────────────────────


def migrate(config_path: str, output_dir: str, *, dry_run: bool = False, overwrite: bool = False) -> bool:
    """Convert an old single-file config to a modular config directory.

    Returns True on success, False on validation failure.
    """
    src = Path(config_path).resolve()
    dest = Path(output_dir).resolve()
    source_dir = src.parent

    # ── Parse old config ─────────────────────────────────────────────────
    old = _load_old_config(src)

    # ── Plan files ───────────────────────────────────────────────────────
    files_to_write: dict[str, str] = {}

    # Domain files: each top-level key (excluding meta) → its own YAML
    for key in DOMAIN_KEYS:
        if key in old:
            files_to_write[f"{key}.yaml"] = GENERATED_HEADER + "\n" + _yaml_dump(old[key])

    # Profile files
    profiles_raw = old.get("profiles", {})
    if isinstance(profiles_raw, dict) and profiles_raw:
        for name, profile_data in profiles_raw.items():
            files_to_write[f"profiles/{name}.yaml"] = (
                GENERATED_HEADER + "\n" + _yaml_dump(profile_data)
            )

    # main.yaml
    main_parts: list[str] = [GENERATED_HEADER]
    for key in DOMAIN_KEYS:
        if key in old:
            main_parts.append(f"{key}: !include {key}.yaml")
    main_parts.append("")

    default_profile = str(old.get("default_profile", "")).strip()
    if default_profile:
        main_parts.append(f"default_profile: {default_profile}")

    if isinstance(profiles_raw, dict) and profiles_raw:
        main_parts.append("")
        main_parts.append("profiles:")
        for name in profiles_raw:
            main_parts.append(f"  {name}: !include profiles/{name}.yaml")

    main_parts.append("")
    files_to_write["main.yaml"] = "\n".join(main_parts)

    # Companion files
    copies: list[tuple[Path, str]] = []
    for src_filename, dst_filename in COMPANION_FILES:
        candidate = source_dir / src_filename
        if candidate.is_file():
            copies.append((candidate, dst_filename))

    # Warn about unrecognised top-level keys
    extra_keys = set(old.keys()) - set(DOMAIN_KEYS) - META_KEYS
    if extra_keys:
        print(f"Warning: Unrecognised top-level keys will not be migrated: {', '.join(sorted(extra_keys))}")
        print("  These keys are neither domain keys nor meta keys and will be lost.")

    # ── Dry run ──────────────────────────────────────────────────────────
    if dry_run:
        count = len(files_to_write) + len(copies)
        print(f"DRY RUN — would create {count} file(s) in {dest}:")
        for fname in sorted(files_to_write):
            print(f"  [WRITE] {fname}")
        for _, dst_name in copies:
            print(f"  [COPY]  {dst_name}")
        print("\nNo files were written.")
        return True

    # ── Write files ──────────────────────────────────────────────────────
    dest.mkdir(parents=True, exist_ok=True)

    created: list[str] = []
    skipped: list[str] = []

    for rel_path, content in files_to_write.items():
        target = dest / rel_path
        if target.exists() and not overwrite:
            skipped.append(rel_path)
        else:
            _write_file(target, content)
            created.append(rel_path)

    for src_path, dst_name in copies:
        target = dest / dst_name
        if target.exists() and not overwrite:
            skipped.append(f"{dst_name} (copy)")
        else:
            shutil.copy2(src_path, target)
            created.append(f"{dst_name} (copy)")

    # ── Report ───────────────────────────────────────────────────────────
    print(f"Migration complete → {dest}")
    if created:
        print(f"  Created {len(created)} file(s):")
        for item in created:
            print(f"    {item}")
    if skipped:
        print(f"  Skipped {len(skipped)} file(s) (use --overwrite to replace):")
        for item in skipped:
            print(f"    {item}")

    # ── Validate round-trip ──────────────────────────────────────────────
    return _validate(dest, old)


# ── Validation ──────────────────────────────────────────────────────────────


def _validate(output_dir: Path, old_config: dict) -> bool:
    """Verify that the migrated files contain the same data as the original."""
    print("\n--- Round-trip validation ---")

    all_ok = True

    # Compare domain data
    for key in DOMAIN_KEYS:
        if key not in old_config:
            continue
        domain_file = output_dir / f"{key}.yaml"
        if not domain_file.is_file():
            print(f"  FAIL: Missing domain file {key}.yaml")
            all_ok = False
            continue
        raw = domain_file.read_text(encoding="utf-8")
        migrated_data = yaml.safe_load(_strip_header(raw))
        if migrated_data is None:
            migrated_data = {}
        if migrated_data != old_config[key]:
            print(f"  MISMATCH: {key}.yaml data differs from original")
            all_ok = False

    # Compare profile data
    old_profiles = old_config.get("profiles", {})
    if isinstance(old_profiles, dict) and old_profiles:
        profiles_dir = output_dir / "profiles"
        if not profiles_dir.is_dir():
            print("  FAIL: Missing profiles/ directory")
            all_ok = False
        else:
            for name, expected in old_profiles.items():
                pf_file = profiles_dir / f"{name}.yaml"
                if not pf_file.is_file():
                    print(f"  FAIL: Missing profile file profiles/{name}.yaml")
                    all_ok = False
                    continue
                raw = pf_file.read_text(encoding="utf-8")
                migrated_data = yaml.safe_load(_strip_header(raw))
                if migrated_data is None:
                    migrated_data = {}
                if migrated_data != expected:
                    print(f"  MISMATCH: profiles/{name}.yaml data differs from original")
                    all_ok = False

    # Compare default_profile
    old_default = old_config.get("default_profile")
    main_text = (output_dir / "main.yaml").read_text(encoding="utf-8")
    if old_default is not None:
        expected_line = f"default_profile: {old_default}"
        if expected_line not in main_text:
            print(f"  MISMATCH: default_profile '{old_default}' not found in main.yaml")
            all_ok = False

    if all_ok:
        print("  PASS — all key/values match the original config.")
    else:
        print("  See mismatches above. Data integrity may be compromised.")

    # Summary stats
    n_profiles = len(old_profiles) if isinstance(old_profiles, dict) else 0
    print(f"  Domains written: {sum(1 for k in DOMAIN_KEYS if k in old_config)}")
    print(f"  Profiles written: {n_profiles}")
    print(f"  default_profile: {old_default or '(none)'}")

    return all_ok


# ── CLI ─────────────────────────────────────────────────────────────────────


def _build_parser() -> argparse.ArgumentParser:
    return argparse.ArgumentParser(
        prog="migrate_config.py",
        description=(
            "Convert an old single-file config.yaml into the new modular "
            "config/ folder structure with !include references."
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""\
Examples:
  python scripts/migrate_config.py tests/config.example.yaml --output config/local/
  python scripts/migrate_config.py config.yaml --output config/local/ --dry-run
  python scripts/migrate_config.py config.yaml --output config/local/ --overwrite
""",
    )


def main(argv: list[str] | None = None) -> None:
    parser = _build_parser()
    parser.add_argument(
        "config",
        help="Path to the old single-file config.yaml",
    )
    parser.add_argument(
        "--output", "-o",
        required=True,
        help="Output directory for the modular config",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print planned files without writing anything to disk",
    )
    parser.add_argument(
        "--overwrite",
        action="store_true",
        help="Overwrite existing files in the output directory (default: skip)",
    )
    args = parser.parse_args(argv)

    success = migrate(
        config_path=args.config,
        output_dir=args.output,
        dry_run=args.dry_run,
        overwrite=args.overwrite,
    )
    if not success:
        sys.exit(1)


if __name__ == "__main__":
    main()
